<div class="page-header columns" style="clear:both">
    <div class="column main">
        <form method="post" action="<?php echo $block->getUrl('*/stroopwafel/results'); ?>">
                <div class="field required">
                    <label class="label" for="search_terms">Search For:</label>
                    <input type="text" name="search_terms" id="search_terms" class="input-text required-entry" />
                    <button type="submit" class="action submit primary" title="Submit"><span>Search</span></button>
                </div>
        </form>
    </div>
</div>
